### ISSUE TITLE
Message error in custom position targetSelector

### ISSUE THREAD

**Issue by begandroide** [ng-turkey/ngx-validate#38]
Im working on angular 9, and i want put the custom component <error-custom-comp> in a special position of material input field; the problem is that the targetSelector: '.special-class', not is being processed, and the custom component message is placed on another targetSelector. How we must use the targetSelector?

**To Reproduce**
In app.module.ts (import section)

```(angular)
NgxValidateCoreModule.forRoot({`
      errorTemplate: ValidationErrorComponent,
      targetSelector: '.special-class',
    }),
  `],
```

**Comment by armanozak** [comment]
Hi @begandroide,

`targetSelector` is passed to InjectionToken as value and is being processed here: https://github.com/ng-turkey/ngx-validate/blob/9dcfd1c636317ca79fd37020967a1e1e930b9120/packages/core/src/lib/directives/validation.directive.ts#L126

I have forked the demo app, upgraded it to Angular 9 and changed the `targetSelector` to `.form-control`:

https://stackblitz.com/edit/ngx-validate-c6biws?file=src%2Fapp%2Fapp.module.ts

As you can see, a solid border replaces the dashed border. This is because, `is-invalid` class is placed on the form control instead of the form group. You can see the styling here:

https://stackblitz.com/edit/ngx-validate-c6biws?file=src%2Fstyles.css

If you set `targetSelector` back to `.form-group`, the dashed border will return.

Please let me know if this answer is clear to you.

P.S. Ivy is not enabled in the demo, because explicit generic type for `ModuleWithProviders` is not applied in this library yet and that is a breaking change when Ivy is enabled.

**Comment by begandroide** [comment]
Hi @armanozak, thanks you very much for the quick response. I understood that `is-invalid` class is placed on the targetSelector, thanks for that. Now the principal problem is that i want place the custom component in a special place (below class `mat-form-field-flex`), and the custom error component still placing below of invalid target.
![image](https://user-images.githubusercontent.com/22018004/77082918-7df23100-69db-11ea-829f-29269874a994.png)
 
![image](https://user-images.githubusercontent.com/22018004/77083250-f9ec7900-69db-11ea-8905-db035cd4fec8.png)

**Comment by armanozak** [comment]
I think placing `validationTarget` on `div.mat-form-field-wrapper` should insert the error component exactly where you wish it to be.

Sorry for missing documentation and features. We have not been able to invest our time in this repo so far, but we intend to do so very soon.

**Comment by begandroide** [comment]
Thank you very much !! works for me 😄
